import type { Metadata } from "next";
import "./globals.css";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  // TODO change the language types
  if (!routing.locales.includes(locale as "en")) {
    notFound();
  }
  // Providing all messages to the client  side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body>
        .............{locale},,,,,,,,,,,,,,,,
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
